### ISSUE TITLE
Create a FAQ page for the guides

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#142]
Giving there has been issue raised for the guides but ended up with a documentation as the best solution, we'd create a FAQ page to host this kind of information for the guides.

**Comment by evelinec** [comment]
@cajaygle, @lauracowen Would you give any suggestions for this page?
@kinueng FYI as well.

**Comment by lauracowen** [comment]
I don't think an FAQ is the right way to present it.

This sounds like troubleshooting info (@NottyCode ) (ie symptom--reason--solution info). I don't completely understand (from my quick reading) when/who will hit the linked problem - it sounds like a general problem, not specific to using our guides, is that right? Is it something people will likely hit, in some situations, when writing any app with OL and Maven?

**Comment by yeekangc** [comment]
A FAQ is an idea.  We should work out what is best.

We have 2 issues that need to be noted, #135 and #140.

**Comment by evelinec** [comment]
Another issue that can be noted in a "FAQ" page, #193, for the OpenJ9 ulimit issue on Mac.

**Comment by cajaygle** [comment]
Is this a troubleshooting page for guide writers (probably best done in git), or a troubleshooting page for guider readers (on the site)?

**Comment by yeekangc** [comment]
More for the readers than the writers at the moment.  For writers, certainly, it makes sense to be on GitHub where guide writing instructions live.

**Comment by cajaygle** [comment]
We are working on revamped docs structure to include new reference documentation.  We'll include such a troubleshooting page as part of the design considerations.  See https://github.com/OpenLiberty/openliberty.io/issues/887

@bsbyrd1

**Comment by cajaygle** [comment]
One more question, do you envision this as a **guides** troubleshooting doc or an Open Liberty troubleshooting doc?   The later, right?  If so, let's move this issue to the docs repo.

**Comment by yeekangc** [comment]
It's for the guides though I really hope we won't need it.  General troubleshooting doc for OL will be a separate item.

**Comment by gkwan-ibm** [comment]
Another topic reported by Graham

> I'm just going through the OpenShift Operator guide and have bumped into this:

```
oc logs build/system-buildconfig-1
oc logs build/inventory-buildconfig-1
Receiving source from STDIN as archive ...
Caching blobs under "/var/cache/blobs".
Pulling image openliberty/open-liberty:full-java11-openj9-ubi ...
Warning: Pull failed, retrying in 5s ...
Warning: Pull failed, retrying in 5s ...
Warning: Pull failed, retrying in 5s ...
error: build error: failed to pull image: After retrying 2 times, Pull image still failed due to error: while pulling "docker://openliberty/open-liberty:full-java11-openj9-ubi" as "openliberty/open-liberty:full-java11-openj9-ubi": Error initializing source docker://openliberty/open-liberty:full-java11-openj9-ubi: Error reading manifest full-java11-openj9-ubi in docker.io/openliberty/open-liberty: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
Receiving source from STDIN as archive ...
Caching blobs under "/var/cache/blobs".
Pulling image openliberty/open-liberty:full-java11-openj9-ubi ...
Warning: Pull failed, retrying in 5s ...
Warning: Pull failed, retrying in 5s ...
Warning: Pull failed, retrying in 5s ...
error: build error: failed to pull image: After retrying 2 times, Pull image still failed due to error: while pulling "docker://openliberty/open-liberty:full-java11-openj9-ubi" as "openliberty/open-liberty:full-java11-openj9-ubi": Error initializing source docker://openliberty/open-liberty:full-java11-openj9-ubi: Error reading manifest full-java11-openj9-ubi in docker.io/openliberty/open-liberty: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

There is a workaround at the ent github /cloudpakbringup/bringup-site/how-to/Fyre/#docker-rate-limiting

**Comment by gkwan-ibm** [comment]
For Win, start dev mode,  create src/main/webapp/WEB-INF/web.xml file by an editor, before paste the content, OL throws an error:
```
[INFO] javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
[INFO] Message: Premature end of file.
[INFO]  at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:652)
[INFO]  at com.ibm.ws.javaee.ddmodel.DDParser.parseToRootElement(DDParser.java:984)
[INFO]  at [internal classes]
[INFO]  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[INFO]  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[INFO]  at java.base/java.lang.Thread.run(Thread.java:857)
[INFO] [ERROR   ] CWWKZ0004E: An exception occurred while starting the application guide-jakarta-faces. The exception message was: java.lang.IllegalStateException: com.ibm.wsspi.adaptable.module.UnableToAdaptException: com.ibm.ws.javaee.ddmodel.DDParser$ParseException: CWWKC2272E: An error occurred while parsing the webapp : WEB-INF/web.xml deployment descriptor on line 1. The error message was: ParseError at [row,col]:[1,1]
[INFO] Message: Premature end of file.
```
FFDC:
```
------Start of DE processing------ = [11/7/24, 8:51:59:813 EST]
Exception = java.lang.IllegalStateException
Source = com.ibm.ws.app.manager.internal.statemachine.StartAction
probeid = 205
Stack Dump = java.lang.IllegalStateException: com.ibm.wsspi.adaptable.module.UnableToAdaptException: com.ibm.ws.javaee.ddmodel.DDParser$ParseException: CWWKC2272E: An error occurred while parsing the webapp : WEB-INF/web.xml deployment descriptor on line 1. The error message was: ParseError at [row,col]:[1,1]
Message: Premature end of file.
	at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.setUpApplicationMonitoring(WARApplicationHandlerImpl.java:54)
	at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:194)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1369)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.performAction(ApplicationStateMachineImpl.java:1233)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:920)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:298)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:857)
Caused by: com.ibm.wsspi.adaptable.module.UnableToAdaptException: com.ibm.ws.javaee.ddmodel.DDParser$ParseException: CWWKC2272E: An error occurred while parsing the webapp : WEB-INF/web.xml deployment descriptor on line 1. The error message was: ParseError at [row,col]:[1,1]
```

**Workaround:**
- new a file without path
- paste the content
- then save the file to the right location
